### PR TITLE
Document export_atlas_scalar

### PR DESCRIPTION
**Pull request by lparsons**
Make it more obvious how to get a scalar version of the atlas by documenting in README.

* Make export_atlas_scalar a proper script
* Document export_atlas_scalar in README
* Remove the now redundant use_mock_atlas_scalar script.

### CODE REVIEW

**Comment by lparsons** [comment]
@francescorandi @aleifer I added the defaults to the help text for the export function to make things more explicit. I also added the required parameter (`--amplitude-threshold 0`) to our internal documentation on how to update the data for this application. 

We could even decide to set the default to zero (`0`) if you think it's appropriate, though I'm not sure what else this script might be used for.

**Comment by aleifer** [comment]
Great. Thank you. Setting default to zero seems like a good idea.

--
Andrew Leifer, Ph.D.
Assistant Professor of Physics & Neuroscience
Princeton University

220 Jadwin (Office) | 118 Jadwin (Lab)
Princeton NJ 08544
Ph (609) 258-8779
***@***.******@***.***>
http://leiferlab.princeton.edu<http://leiferlab.princeton.edu/>



From: Lance Parsons ***@***.***>
Date: Friday, June 9, 2023 at 4:40 PM
To: leiferlab/worm-functional-connectivity ***@***.***>
Cc: Andrew M. Leifer ***@***.***>, Mention ***@***.***>
Subject: Re: [leiferlab/worm-functional-connectivity] Document export_atlas_scalar (PR #15)

@francescorandi<https://github.com/francescorandi> @aleifer<https://github.com/aleifer> I added the defaults to the help text for the export function to make things more explicit. I also added the required parameter (--amplitude-threshold 0) to our internal documentation on how to update the data for this application.

We could even decide to set the default to zero (0) if you think it's appropriate, though I'm not sure what else this script might be used for.

**Comment by lparsons** [comment]
Thanks, I set the default to zero (0) in this PR.

**Comment by lparsons** [comment]
@aleifer @francescorandi Would anyone mind if I merged this PR as well as #14?

**Pull request merged**
